# application.yml

spring:
  profiles:
    active: dev
  application:
    name: resume-service
  datasource:
    url: ${RESUME_DATASOURCE_URL}
    username: ${RESUME_DATASOURCE_USERNAME}
    password: ${RESUME_DATASOURCE_PASSWORD}
    tomcat:
      test-while-idle: true
      validation-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: validate
