spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kuaidaoresume_resume?useUnicode=true&characterEncoding=utf-8
    #url: jdbc:mysql://kuaidaoresume-resume.cm27uwrvuert.ca-central-1.rds.amazonaws.com:3306/kuaidaoresume-resume?useUnicode=true&characterEncoding=utf-8
    username: root
    password:
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
  data:
    rest:
      base-path: /api
server:
  port: 8082
management:
  endpoints:
    web:
      exposure:
        include: "*"
