spring:
  datasource:
    url: jdbc:mysql://kuaidaoresume-resume.cm27uwrvuert.ca-central-1.rds.amazonaws.com:3306/kuaidaoresume-resume?useUnicode=true&characterEncoding=utf-8
    username: root
    password: mysqlroot
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  data:
    rest:
      base-path: /api
server:
  port: 8082
management:
  endpoints:
    web:
      exposure:
        include: "*"

kuaidaoresume:
  common:
    sentry-dsn: ${SENTRY_DSN:https://270864132b0845e4a9ae4f68f96c77c2@o434398.ingest.sentry.io/5391423}
    deploy-env: ${DEPLOY:V2}
  signing-secret: ${SIGNING_SECRET}
  #bot-service-endpoint: ${BOT_SERVICE_ENDPOINT:http://bot-service:8080}
  intercom-access-token: ${INTERCOM_ACCESS_TOKEN}