server:
  port: 8084

spring:
  profiles:
    active: dev
  jpa:
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

kuaidaoresume:
  account-service-endpoint: http://localhost:8081
