version: '3.7'

services:
  account-service:
    build: ./account-svc
    image: kuaidaoresume/account-svc
    environment:
      - SPRING_PROFILES_ACTIVE
      - SERVER_PORT
      - SIGNING_SECRET
      - SENTRY_DSN
      - EMAIL_SERVICE_ENDPOINT
      #- BOT_SERVICE_ENDPOINT
      - ACCOUNT_DATASOURCE_URL
      - ACCOUNT_DATASOURCE_USERNAME
      - ACCOUNT_DATASOURCE_PASSWORD
    depends_on:
      - email-service
    networks:
      - internal_access
      - external_access # db access

  resume-service:
    build: ./resume-svc
    image: kuaidaoresume/resume-svc
    environment:
      - SPRING_PROFILES_ACTIVE
      - SERVER_PORT
      - SIGNING_SECRET
      - RESUME_DATASOURCE_URL
      - RESUME_DATASOURCE_USERNAME
      - RESUME_DATASOURCE_PASSWORD
    networks:
      - internal_access
      - external_access # db access

  job-service:
    build: ./job-svc
    image: kuaidaoresume/job-svc
    environment:
      - SPRING_PROFILES_ACTIVE
      - SERVER_PORT
      - SENTRY_DSN
      - SIGNING_SECRET
      - JOB_DATASOURCE_URL
      - JOB_DATASOURCE_USERNAME
      - JOB_DATASOURCE_PASSWORD
    networks:
      - internal_access
      - external_access # db access

  rabbitmq3:
    image: rabbitmq:3-management
    networks:
      - internal_access

  job-fetcher:
    build: ./job-fetcher
    environment:
      - SENTRY_DSN
    image: kuaidaoresume/job-fetcher
    networks:
      - internal_access
      - external_access # serpapi
    depends_on:
      - rabbitmq3
      - job-service

  matching-listener:
    build: ./matching-listener
    environment:
      - SENTRY_DSN
    image: kuaidaoresume/matching-listener
    networks:
      - internal_access
    depends_on:
      - rabbitmq3
      - job-fetcher

  email-service:
    build: ./mail-svc
    image: kuaidaoresume/mail-svc
    environment:
      - SPRING_PROFILES_ACTIVE
      - SERVER_PORT
      - SENTRY_DSN
      - AWS_ACCESS_KEY
      - AWS_ACCESS_SECRET
    networks:
      - internal_access
      - external_access # aws access

  whoami-service:
    build: ./whoami-svc
    image: kuaidaoresume/whoami-svc
    environment:
      - SPRING_PROFILES_ACTIVE
      - SERVER_PORT
      - SENTRY_DSN
      - ACCOUNT_SERVICE_ENDPOINT
    depends_on:
      - account-service
    networks:
      - internal_access

  www-service:
    build: ./onboarding-app
    image: kuaidaoresume/www-svc
    environment:
      - SPRING_PROFILES_ACTIVE
      - SERVER_PORT
      - SENTRY_DSN
      - SIGNING_SECRET
      - ACCOUNT_SERVICE_ENDPOINT
      - EMAIL_SERVICE_ENDPOINT
      - RECAPTCHA_PUBLIC
      - RECAPTCHA_PRIVATE
    depends_on:
      - account-service
      - email-service
    networks:
      - internal_access

  kdr-service:
    build: ./kdr
    image: kuaidaoresume/kdr-svc
    ports:
      - 80:80
    environment:
      - SPRING_PROFILES_ACTIVE
      - SERVER_PORT
      - SENTRY_DSN
      - SIGNING_SECRET
    depends_on:
      - account-service
      - resume-service
      - www-service
      - whoami-service
      - job-service
    networks:
      - internal_access
      - external_access

networks:
  internal_access:
    internal: true
  external_access:
