version: '3.7'

services:
  account-service:
    build: ./account-svc
    image: kuaidaoresume/account-svc
    environment:
      - SPRING_PROFILES_ACTIVE
      - SERVER_PORT
      - SIGNING_SECRET
      #- SENTRY_DSN
      #- BOT_SERVICE_ENDPOINT
      - ACCOUNT_DATASOURCE_URL
      - ACCOUNT_DATASOURCE_USERNAME
      - ACCOUNT_DATASOURCE_PASSWORD
    networks:
      - internal_access
      - external_access # db access

  kdr-service:
    build: ./kdr
    image: kuaidaoresume/kdr-svc
    ports:
      - 80:80
    environment:
      - SPRING_PROFILES_ACTIVE
      - SERVER_PORT
      - SENTRY_DSN
      - SIGNING_SECRET
    depends_on:
      - account-service
      #- job-service
      #- resume-service
      #- www-service
      #- whoami-service
#      - ical-service # commented for demo
    networks:
      - internal_access
      - external_access

networks:
  internal_access:
    internal: true
  external_access:
