# application.yml

spring:
  profiles:
    active: dev
  application:
    name: email-service

# local test only
cloud.aws.stack.auto: false
cloud.aws.region.auto: false
cloud.aws.region.static: ca-central-1

kuaidaoresume:
  common:
    sentry-dsn: ${SENTRY_DSN:https://270864132b0845e4a9ae4f68f96c77c2@o434398.ingest.sentry.io/5391423}
    deploy-env: ${DEPLOY:V2}
  aws-access-key: ${AWS_ACCESS_KEY}
  aws-access-secret: ${AWS_ACCESS_SECRET}