apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: kdr-prod
  region: us-west-2

iam:
  withOIDC: true

managedNodeGroups:
  - name: managed-ng-1
    instanceType: m5.2xlarge
    minSize: 3
    maxSize: 5
    ssh:
      allow: true
      publicKeyPath: ~/.ssh/id_rsa.pub

cloudWatch:
  clusterLogging:
    enableTypes: ["*"]
