apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: kdr-prod
  region: us-west-2

iam:
  withOIDC: true
  serviceAccounts:
    - metadata:
        name: rds-db-access
        namespace: default
        labels: {role: "backend"}
      attachPolicyARNs:
        - "arn:aws:iam::775359692517:policy/RDS_IAM_access"
