# https://matthewpalmer.net/kubernetes-app-developer/articles/kubernetes-apiversion-definition-guide.html
apiVersion: apps/v1
kind: Deployment
metadata:
  name: matching-svc-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matching-svc
  template:
    metadata:
      labels:
        app: matching-svc
        env: prod
    spec:
      containers:
        - name: matching-svc
          image: kuaidaoresume/matching-svc
          imagePullPolicy: Always
          ports:
            - name: http-port
              containerPort: 80
          envFrom:
            - configMapRef:
                name: common-config
          volumeMounts:
            - name: logback-config-volume
              mountPath: /etc/kuaidaoresume
      volumes:
        - name: logback-config-volume
          configMap:
            name: logback-config
---
apiVersion: v1
kind: Service
metadata:
  name: matching-service
spec:
  selector:
    app: matching-svc
    env: prod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
