apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq3
spec:
  serviceName: rabbitmq
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq3
  template:
    metadata:
      labels:
        app: rabbitmq3
        env: prod
    spec:
      containers:
        - name: rabbitmq3
          image: rabbitmq:3-management
          imagePullPolicy: IfNotPresent
          ports:
            - name: additional-port
              containerPort: 5672
          envFrom:
            - configMapRef:
                name: common-config
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq3
spec:
  selector:
    app: rabbitmq3
    env: test
  ports:
    - protocol: TCP
      port: 5672
      targetPort: 5672