# https://matthewpalmer.net/kubernetes-app-developer/articles/kubernetes-apiversion-definition-guide.html
apiVersion: apps/v1
kind: Deployment
metadata:
  name: resume-svc-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: resume-svc
  template:
    metadata:
      labels:
        app: resume-svc
        env: prod
    spec:
      containers:
        - name: resume-svc
          image: kuaidaoresume/resume-svc
          imagePullPolicy: Always
          ports:
            - name: http-port
              containerPort: 80
          envFrom:
            - configMapRef:
                name: common-config
          volumeMounts:
            - name: logback-config-volume
              mountPath: /etc/kuaidaoresume
      volumes:
        - name: logback-config-volume
          configMap:
            name: logback-config
---
apiVersion: v1
kind: Service
metadata:
  name: resume-service
spec:
  selector:
    app: resume-svc
    env: prod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
