# application.yml
spring:
  profiles:
    active: dev
  application:
    name: account-service
  datasource:
    url: ${ACCOUNT_DATASOURCE_URL}
    username: ${ACCOUNT_DATASOURCE_USERNAME}
    password: ${ACCOUNT_DATASOURCE_PASSWORD}
    tomcat:
      test-while-idle: true
      validation-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: validate

kuaidaoresume:
  common:
    sentry-dsn: ${SENTRY_DSN:https://270864132b0845e4a9ae4f68f96c77c2@o434398.ingest.sentry.io/5391423}
    deploy-env: ${DEPLOY:V2}
  signing-secret: ${SIGNING_SECRET}
  email-service-endpoint: ${EMAIL_SERVICE_ENDPOINT:http://email-service:8080}
  #bot-service-endpoint: ${BOT_SERVICE_ENDPOINT:http://bot-service:8080}
  intercom-access-token: ${INTERCOM_ACCESS_TOKEN}
