# https://matthewpalmer.net/kubernetes-app-developer/articles/kubernetes-apiversion-definition-guide.html
apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-svc-deployment
  #namespace: kuaidaoresume-uat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: job-svc
  template:
    metadata:
      labels:
        app: job-svc
        env: uat
    spec:
      containers:
        - name: job-svc
          image: kuaidaoresume/job-svc
          imagePullPolicy: Always
          ports:
            - name: http-port
              containerPort: 80
          envFrom:
            - configMapRef:
                name: common-config
          volumeMounts:
            - name: logback-config-volume
              mountPath: /etc/kuaidaoresume
      volumes:
        - name: logback-config-volume
          configMap:
            name: logback-config
---
apiVersion: v1
kind: Service
metadata:
  name: job-service
spec:
  selector:
    app: job-svc
    env: uat
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
