# https://matthewpalmer.net/kubernetes-app-developer/articles/kubernetes-apiversion-definition-guide.html
# https://stackoverflow.com/questions/53775328/kubernetes-port-forwarding-error-listen-tcp4-127-0-0-188-bind-permission-de
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kdr-svc-deployment
  #namespace: kuaidaoresume-uat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kdr-svc
  template:
    metadata:
      labels:
        app: kdr-svc
        env: uat
    spec:
      containers:
        - name: kdr-svc
          image: kuaidaoresume/kdr-svc
          imagePullPolicy: Always
          ports:
            - name: http-port
              containerPort: 80
          envFrom:
            - configMapRef:
                name: common-config
          volumeMounts:
            - name: logback-config-volume
              mountPath: /etc/kuaidaoresume
      volumes:
        - name: logback-config-volume
          configMap:
            name: logback-config
---
apiVersion: v1
kind: Service
metadata:
  name: kdr-service
spec:
  selector:
    app: kdr-svc
    env: uat
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
