apiVersion: apps/v1
kind: Deployment
metadata:
  name: matching-listener-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matching-listener
  template:
    metadata:
      labels:
        app: matching-listener
        env: uat
    spec:
      containers:
        - name: matching-listener
          image: kuaidaoresume/matching-listener
          imagePullPolicy: Always
          ports:
            - name: additional-port
              containerPort: 5672
          envFrom:
            - configMapRef:
                name: common-config
          volumeMounts:
            - name: logback-config-volume
              mountPath: /etc/kuaidaoresume
      volumes:
        - name: logback-config-volume
          configMap:
            name: logback-config
---
apiVersion: v1
kind: Service
metadata:
  name: matching-listener
spec:
  selector:
    app: matching-listener
    env: uat
  ports:
    - protocol: TCP
      port: 5672
      targetPort: 5672
