# https://matthewpalmer.net/kubernetes-app-developer/articles/kubernetes-apiversion-definition-guide.html
apiVersion: apps/v1
kind: Deployment
metadata:
  name: resume-svc-deployment
  #namespace: kuaidaoresume-uat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resume-svc
  template:
    metadata:
      labels:
        app: resume-svc
        env: uat
    spec:
      containers:
        - name: resume-svc
          image: kuaidaoresume/resume-svc
          imagePullPolicy: Never
          ports:
            - name: http-port
              containerPort: 80
          envFrom:
            - configMapRef:
                name: common-config
---
apiVersion: v1
kind: Service
metadata:
  name: resume-service
spec:
  selector:
    app: resume-svc
    env: uat
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
