# application.yml

spring:
  application:
    name: www-service

server:
  error:
    whitelabel:
      enabled: false

kuaidaoresume:
  common:
    sentry-dsn: ${SENTRY_DSN:https://270864132b0845e4a9ae4f68f96c77c2@o434398.ingest.sentry.io/5391423}
    deploy-env: ${DEPLOY:V2}
  signing-secret: ${SIGNING_SECRET}
  email-service-endpoint: ${EMAIL_SERVICE_ENDPOINT:http://email-service:8080}
  account-service-endpoint: ${ACCOUNT_SERVICE_ENDPOINT:http://account-service:8080}
  recaptcha-public: ${RECAPTCHA_PUBLIC}
  recaptcha-private: ${RECAPTCHA_PRIVATE}
