# https://matthewpalmer.net/kubernetes-app-developer/articles/kubernetes-apiversion-definition-guide.html
apiVersion: apps/v1
kind: Deployment
metadata:
  name: www-web-deployment-canary
  namespace: kuaidaoresume-uat
spec:
  replicas: 1
    selector:
      matchLabels:
        app: www-svc
  template:
    metadata:
      labels:
        app: www-svc
        env: uat
        track: canary
    spec:
      containers:
        - name: www-svc
          image: kuaidaoresume/www-svc:blue
          ports:
            - name: http-port
              containerPort: 80
          envFrom:
            - configMapRef:
                name: common-config
          volumeMounts:
            - name: logback-config-volume
              mountPath: /etc/kuaidaoresume
      volumes:
        - name: logback-config-volume
          configMap:
            name: logback-config
