spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kuaidaoresume_job?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: mysqlroot
  jpa:
    show-sql: true
  data:
    rest:
      base-path: /api
server:
  port: 8083
management:
  endpoints:
    web:
      exposure:
        include: "*"
