# application.yml
spring:
  application:
    name: job-service
  datasource:
    url: ${JOB_DATASOURCE_URL:jdbc:mysql://kuaidaoresume-job.cm27uwrvuert.ca-central-1.rds.amazonaws.com:3306/kuaidaoresume_job?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC}
    username: ${JOB_DATASOURCE_USERNAME:root}
    password: ${JOB_DATASOURCE_PASSWORD:~Youkn0wit)-j0b}
    tomcat:
      test-while-idle: true
      validation-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: validate

kuaidaoresume:
  common:
    sentry-dsn: ${SENTRY_DSN:https://270864132b0845e4a9ae4f68f96c77c2@o434398.ingest.sentry.io/5391423}
    deploy-env: ${DEPLOY:V2}
  signing-secret: ${SIGNING_SECRET}
  intercom-access-token: ${INTERCOM_ACCESS_TOKEN}
  cache:
    job:
      policy:
        max-size-policy: ${JOB_CACHE_POLICY_MAXSIZE:PER_NODE}
        eviction-policy: ${JOB_CACHE_POLICY_EVICTION:LRU}
    job-search:
      policy:
        max-size-policy: ${JOB_SEARCH_CACHE_POLICY_MAXSIZE:PER_NODE}
        eviction-policy: ${JOB_SEARCH_CACHE_POLICY_EVICTION:LFU}
