spring:
  profiles:
    active: dev

server:
  port: 8087
kuaidaoresume:
  job-service-endpoint: http://localhost:8083
  resume-service-endpoint: http://localhost:8082
  email-service-endpoint: http://localhost:8088
management:
  endpoints:
    web:
      exposure:
        include: "*"
