# application.yml
spring:
  application:
    name: matching-service
  data:
    mongodb:
      uri: ${MATCHING_DATASOURCE_URL:mongodb+srv://uat:mongodbroot@kuaidaoresume-uat1.kxcvj.mongodb.net}
      database: kuaidaoresume-matching
      auto-index-creation: true

kuaidaoresume:
  common:
    sentry-dsn: ${SENTRY_DSN:https://270864132b0845e4a9ae4f68f96c77c2@o434398.ingest.sentry.io/5391423}
    deploy-env: ${DEPLOY:V2}
  signing-secret: ${SIGNING_SECRET}
  email-service-endpoint: ${EMAIL_SERVICE_ENDPOINT:http://email-service:8080}
  job-service-endpoint: ${JOB_SERVICE_ENDPOINT:http://job-service:8080}
  resume-service-endpoint: ${RESUME_SERVICE_ENDPOINT:http://resume-service:8080}
  intercom-access-token: ${INTERCOM_ACCESS_TOKEN}
  matching:
    caching:
      maximum-size: ${MATCHING_CACHING_MAXIMUM_SIZE:100000}
