name: Webapp CI with Node

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  webapp-build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install -g yarn # Extra Step
    - name: setup, build and test
      run: |
        cd webapp
        yarn
        yarn build:ci
        yarn test:nowatch